export type BlogSection = {
  heading: string;
  paragraphs: string[];
  figures?: BlogFigure[];
};

export type BlogFigure = {
  kind: 'service-models' | 'asp-vs-saas' | 'major-developments' | 'image';
  afterParagraph: number;
  title: string;
  caption?: string;
  imageSrc?: string;
  imageAlt?: string;
};

export type BlogPost = {
  slug: string;
  title: string;
  createdAt: string;
  category: string;
  summary: string;
  coverImage?: string;
  sourcePdf?: string;
  sections: BlogSection[];
  citations?: string[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: 'cloud-computing-origins-history-services',
    title:
      'The Origin, History, Features, Services, Major Players, Competitors, and Examples of Successful Implementation of Cloud Computing',
    createdAt: 'Oct 2, 2024',
    category: 'Research',
    summary:
      'A discussion of cloud computing, including its definition, origin, history, services, and major players, as well as some examples of its successful implementation today.',
    coverImage: '/images/blog/cloud-blog.svg',
    sourcePdf: '/blog/research-project-1.pdf',
    citations: [
      'Armstrong, Martin. “Infographic: Netflix Is Responsible for 15% of Global Internet Traffic.” Statista Infographics, 1 Mar. 2023, www.statista.com/chart/15692/distribution-of-global-downstream-traffic/. Accessed 2 Oct. 2024.',
      '“Azure Updates | Microsoft Azure.” Azure.microsoft.com, azure.microsoft.com/en-us/updates. Accessed 2 Oct. 2024.',
      'Barr, Jeff. “EC2 Instance History.” Amazon Web Services, 28 May 2015, aws.amazon.com/blogs/aws/ec2-instance-history/. Accessed 2 Oct. 2024.',
      'Chandler, Robert, and Marc Chalé. “Harnessing the Momentum of Generative AI.” Phalanx, vol. 56, no. 2, 2023, pp. 52–54. JSTOR, https://www.jstor.org/stable/27227084. Accessed 2 Oct. 2024.',
      '“Conversation with Eric Schmidt hosted by Danny Sullivan, Search Engine Strategies Conference.” Www.google.com, www.google.com/press/podium/ses2006.html. Accessed 2 Oct. 2024.',
      'Coveney, Peter V. “Scientific Grid Computing.” Philosophical Transactions: Mathematical, Physical and Engineering Sciences, vol. 363, no. 1833, 2005, pp. 1707–13. JSTOR, http://www.jstor.org/stable/30039684. Accessed 2 Oct. 2024.',
      'Darpa.mil, 2021, www.darpa.mil/about-us/timeline/ipto. Accessed 2 Oct. 2024.',
      'Denning, Peter J. “The Science of Computing: The ARPANET after Twenty Years.” American Scientist, vol. 77, no. 6, 1989, pp. 530–34. JSTOR, http://www.jstor.org/stable/27856002. Accessed 2 Oct. 2024.',
      'Englander, Irv, and Wilson Wong. The Architecture of Computer Hardware, Systems Software, and Networking: An Information Technology Approach, 6th Edition, edited by Jennifer Manias, Lise Johnson, 2021. Accessed 2 Oct. 2024.',
      'Fano, R. M., and F. J. Corbató. “TIME-SHARING ON COMPUTERS.” Scientific American, vol. 215, no. 3, 1966, pp. 128–43. JSTOR, http://www.jstor.org/stable/24931051. Accessed 2 Oct. 2024.',
      `Foster, I., and C. Kesselman. "The Globus project: a status report," Proceedings Seventh Heterogeneous Computing Workshop (HCW'98), Orlando, FL, USA, 1998, pp. 4-18, doi: 10.1109/HCW.1998.666541. Accessed 2 Oct. 2024.`,
      'Foster, Ian. “THE GRID: Computing without Bounds.” Scientific American, vol. 288, no. 4, 2003, pp. 78–85. JSTOR, http://www.jstor.org/stable/26060247. Accessed 2 Oct. 2024.',
      'GLOBUS. Home. Accessed 2 Oct. 2024.',
      'Hafner, Katie. “Lawrence Roberts, Who Helped Design Internet’s Precursor, Dies at 81.” The New York Times, 30 Dec. 2018, www.nytimes.com/2018/12/30/obituaries/lawrence-g-roberts-dies-at-81.html.',
      'Head, Lauren Lawley. “Companies Selling Software as Service.” GALE ACADEMIC ONEFILE, American City Business Journals, Inc., go-gale-com.mutex.gmu.edu/ps/i.do?id=GALE%7CA55777629&sid=googleScholar&v=2.1&it=r&linkaccess=abs&issn=10968636&p=AONE&sw=w&aty=ip&enforceAuth=true&linkSource=delayedAuthFullText&oweAuth=true&userGroupName=viva_gmu&u=viva_gmu. Accessed 2 Oct. 2024.',
      'Microsoft. “The Coca-Cola Company and Microsoft Announce Five-Year Strategic Partnership to Accelerate Cloud and Generative AI Initiatives.” Stories, 23 Apr. 2024, news.microsoft.com/2024/04/23/the-coca-cola-company-and-microsoft-announce-five-year-strategic-partnership-to-accelerate-cloud-and-generative-ai-initiatives/. Accessed 2 Oct. 2024.',
      'Microsoft. “What Is Cloud Computing? A Beginner’s Guide | Microsoft Azure.” Azure.microsoft.com, 2023, azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-cloud-computing. Accessed 2 Oct. 2024.',
      'OpenAI. “About OpenAI.” OpenAI, OpenAI, 2023, openai.com/about/. Accessed 2 Oct. 2024.',
      'Pelkey, James L. “Chapter 4 - Networking: Vision and Packet Switching 1959 - 1968.” The History Of Computer Communications, 2021. Accessed 2 Oct. 2024.',
      'Regalado, Antonio. “Who Coined ‘Cloud Computing’?” MIT Technology Review, 31 Oct. 2011, www.technologyreview.com/2011/10/31/257406/who-coined-cloud-computing/. Accessed 2 Oct. 2024.',
      'Susarla, Anjana, et al. “A Transaction Cost Perspective of the ‘Software as a Service’ Business Model.” Journal of Management Information Systems, vol. 26, no. 2, 2009, pp. 205–40. JSTOR, http://www.jstor.org/stable/40398986. Accessed 2 Oct. 2024.',
      'Tanenbaum, Andrew S., and Sape J. Mullender. “An Overview of the Amoeba Distributed Operating System.” ACM SIGOPS Operating Systems Review, vol. 15, no. 3, 1 July 1981, pp. 51–64, https://doi.org/10.1145/1041500.1041502. Accessed 2 Oct. 2024.',
      '“Time-Sharing.” IBM, www.ibm.com/history/time-sharing. Accessed 2 Oct. 2024.',
      'van Steen, Maarten, and Andrew S. Tanenbaum. “Introduction.” Distributed Systems, Maarten van Steen, 2017, 2. Accessed 2 Oct. 2024.',
    ],
    sections: [
      {
        heading: 'Introduction',
        paragraphs: [
          'I plan to discuss cloud computing, including its definition, origin, history, services, and major players, as well as some examples of its successful implementation today. This will involve the major cloud computing services including storage-, desktop-, software-, platform-, and infrastructure-services; conceptual origins such as time-sharing, Dr. J. C. R. Licklider’s intergalactic computer network, packet-switching, the Advanced Research Projects Agency (ARPA), the internet, transport control protocol (TCP) and internet protocol (IP) (networked computing), distributed computing, and grid computing and virtual organizations; the true beginning from application server providers (ASPs) to the first record of the term cloud computing; developments by the major players, Amazon Web Services (AWS), Microsoft Azure, and Google Cloud; and successful large-scale implementation by Netflix, Spotify, and Coca-Cola.',
        ],
      },
      {
        heading: 'The Concept of Cloud Computing',
        paragraphs: [
          'In The Architecture of Computer Hardware, Systems Software, and Networking: An Information Technology Approach, 6th Edition, Irv Englander and Wilson Wong say that, “the basic premise of cloud computing is that many functions of an organization’s data center can be moved to services on the Internet, ‘in the cloud,’” (Englander & Wong 441). Microsoft Azure’s A beginner’s guide describes cloud computing as such: “Simply put, cloud computing is the delivery of computing services—including servers, storage, databases, networking, software, analytics, and intelligence—over the internet, or the cloud, to offer faster innovation, flexible resources, and economies of scale,” (Microsoft). Further, cloud computing is usually categorized into various types of services, which are the types of products sold by cloud providers and employed by users or companies, each with its own unique purpose. These include, but are not limited to, Storage as a Service (STaaS), Desktop as a Service (DaaS), Software as a Service (SaaS), Platform as a Service (PaaS), and Infrastructure as a Service (IaaS), which I will describe briefly here. ',
          'Storage as a Service (STaaS) is the most straightforward form of cloud service. It simply provides off-site storage facilities for individuals and organizations. This storage might function as a backup resource, immediate emergency recovery, or perhaps a way to give users access to files from anywhere the internet is available. This is convenient because increased amounts of cloud storage can be paid for as-needed, so clients can spend money on only what they need at any given time while maintaining flexibility for an increase or decrease in storage needs later on. ',
          'Desktop as a Service (DaaS) lets users access a virtual desktop, usually including the OS, cloud applications, automated updates, and scheduled data backups. This can grant users the same experience whether they work remotely or in the office, and affords them the convenience of not needing to manage and upkeep the desktop themselves. ',
          'Software as a Service (SaaS) provides software applications which run on a cloud server and deliver the results to the client’s display. This not only means the client doesn’t need to worry about software installation and updates, but that they can also run software which would usually be too demanding for their own machine, since the cloud servers run the software themselves and simply deliver the results on the client’s display. In some cases, processing is divided between the cloud server and the client, which might allow the client to put a set amount of demand upon their own machine while giving the rest to the cloud server, which simultaneously means that each side doesn’t have to take on more demand than it might really need to. “As an example, Microsoft Office 365 is the cloud version of the desktop suite of applications known collectively as Microsoft Office 2019. Users pay a monthly subscription fee in order to access Microsoft Office 365 over the Internet using a Web browser. Having all users run software applications on the cloud simplifies software updates because only the application server needs to be updated,” (Wilson & Wong 441). ',
          '“Platform as a Service (PaaS) expands cloud services to the software facilities that one  would expect to find on a developer’s computer: Web and programming development tools,  facilities, a Web server, and OS application program interface (API),” (Wilson & Wong 442). This means developers can create and run their own application software on the cloud platform without investing in the hardware and software to support local development.',
          'Infrastructure as a Service (IaaS) emulates hardware, meaning the computer has been moved entirely to the cloud and can be configured at will. The hardware emulation happens in the form of virtual machines, networking, etc. Clients can interact with the machine, usually via a Web browser, or perhaps a client application. The benefit here is that a client would be able to configure a ‘weak’ computer if they only wanted to use it for less demanding purposes, but they would also be able to reconfigure it to a ‘stronger’ machine with more powerful components, should they need to use it for more demanding purposes at any given time. ',
          'There are numerous other types of cloud computing services offered, but these provide a basic set of standout services which have certainly come to define a significant part of what cloud computing is today. ',
        ],
      },
      {
        heading: 'Early Innovations Leading to Cloud Computing',
        figures: [
          {
            kind: 'service-models',
            afterParagraph: -1,
            title: 'Cloud Computing Service Architecture Differences (Ch. 2, Slide 26) - Figure A',
          },
        ],
        paragraphs: [
          'Cloud computing, as it is known and contextualized today, originated around the 1990s to 2000s. However, like many aspects of computer history, its true root is somewhat elusive, as many of the concepts which led to its development are scattered up to 74 years prior to its modern beginning, and beyond.',
          'Time-sharing paved the way for modern cloud computing. In 1922, Thomas J. Watson Sr., president of the Computing-Tabulating-Recording Company, later renamed the International Business Machines Corporation (IBM), realized that many businesses would benefit from tabulators to help with things like billing and payroll but may have been too small to afford their own machine. He had the idea to allow users to send their data to the Service Bureau on punched cards which would run through a tabulating machine, then deliver the reported results back to the user for a fee. This was the seed that would turn into the fundamental advanced computing principle known as time-sharing in which users were enabled to “share” processing time (IBM). ',
          'Over the years, this early method of time-sharing began to feel inefficient. Users had to deliver their problem or program to a receptionist then wait hours or days for an answer which would have likely only taken the machine mere seconds to actually complete. Essentially, the “human” side of the logistics was limiting service time significantly compared to the actual speed of the machine in use. In 1959, the first time-sharing system was proposed by Christopher Strachey as a solution to this issue. His idea was to segregate the central processing operations from the time-consuming interactions with the human programmers, allowing the computer to work on several programs simultaneously, in effect (Fano & Corbató 129). ',
          'The Computation Center at Massachusetts Institute of Technology (MIT) took up Strachey’s idea. By November of 1961, they had developed an initial model of the Compatible Time-Sharing System using an IBM 709 computer. By 1963, they had an improved version of this system operating on two IBM 7094 computers. By then, three other time-sharing systems had also been developed: one at Bolt, Beranek and Newman, Inc., another at M.I.T.’s Research Laboratory of Electronics, and the last at the System Development Corporation. Several more were developed at various research institutions thereafter.  	',
          '	In the midst of all this	was a man named Dr. J. C. R. Licklider, an American computer scientist who became the first Director of the Information Processing Techniques Office (IPTO) of the Advanced Research Projects Agency (ARPA) in October of 1962. Dr. Licklider, “had a vision of computing vastly grander than time-sharing,” (Pelkey) envisioning an intergalactic computer network, where computing resources would be shared across a global network. But he was ahead of his time. In a memo to computer scientists made in April of 1963, Dr. Licklider said, “the term ‘Intergalactic Network’ was a kind of intentionally grandiloquent way to express the idea, because we didn’t really expect to get at that right away. It was all we could possibly do to make timesharing systems work,” (Pelkey). “Knowing it would take all the resources and management he had at his disposal to implement the desired number of time-sharing projects, he decided to leave the issues of interconnecting the time-shared computers for the future,” (Pelkey). Dr. Licklider, “advanced the state of many basic ideas, especially time-sharing,” (Pelkey) in his time before eventually passing away in June of 1990, just a handful of years before cloud computing, as we know it today, began to really begin, so to speak. Although Dr. Licklider never saw his intergalactic computer network vision fully realized, I believe that it has been largely realized in modern cloud computing today, and we certainly owe him a great thanks for his contributions to the field which have led us to this. ',
          'When Sputnik I launched on October 4, 1957, the United States Department of Defense (DoD) responded by establishing the Advanced Research Projects Agency (ARPA) in 1958 with, “a commitment … that, from that time forward, [the U.S.] would be the initiator and not the victim of strategic technological surprises,” (DARPA). Because of the Cold War, there was motivation to develop a decentralized communication network which would be able to survive nuclear attacks; this led to the development of packet-switching, where data is broken into small packets and sent through various network paths, allowing the data to be delivered even if a path was compromised. Then, in 1966, Robert Taylor, Licklider’s successor as third head of ARPA’s IPTO, hired Lawrence Roberts to, “oversee the technical structure of the Arpanet,” (Hafner) which became the first packet-switched network, as opposed to earlier circuit-switched systems. The ARPANET’s first four nodes were at the University of California, Los Angeles (UCLA), Stanford Research Institute (SRI), University of California, Santa Barbara (UCSB), and the University of Utah. The first successful communication occurred in 1969 between UCLA and SRI, marking the birth of the internet. Though electronic mail wasn’t a goal of ARPANET at the time, it accounted for most of the traffic by 1971 and, by the mid-1970s, it was clear that research networking was growing so swiftly that ARPANET would need to connect to other networks. This inspired ARPANET’s end-to-end protocol, network control protocol (NCP), to be reworked into a pair of protocols: transport control protocol (TCP) and internet protocol (IP). TCP/IP enabled the network to expand globally and integrate with other networks, or networked computing, which led to the development of the internet (Denning 530). ',
          'The growing accessibility of networked computing sparked a rise in collaborative computing as well, since computers were now much more able to work together across a network. In the early 1980s, researchers began formalizing the study of system concepts which allow multiple computers to work together effectively. This gave birth to distributed systems, which is, “a collection of autonomous computing elements that appears to its users as a single coherent system,” (van Steen) and the term distributed computing became common in academic study and literature. Examples of this include Andrew Tanenbaum’s Amoeba, a distributed operating system (OS) which allowed multiple processors to communicate and share resources (Tanenbaum & Sape), as well as Digital Equipment Corporation (DEC)’s VAXclusters which allowed multiple VAX computers to work as a single system, enabling resource sharing and parallel processing. ',
          'From distributed computing, researchers started to explore the possibilities of having collaborative groups dynamically sharing resources and machine capabilities across various organizations and across networked distances. Resources like CPU cycles, storage space, and data could be shared by multiple computers, often owned by different organizations or individuals, for collaborative work which could tackle more complex projects. This coordinated distributed computing model became known as grid computing. The similarities between this and cloud computing are clear. The groups that used grid computing became known as virtual organizations. The Globus project, “a multi-institutional research effort that seeks to enable the construction of computational grids providing pervasive, dependable, and consistent access to high-performance computational resources, despite geographical distribution of both resources and users,” (Foster & Kesselman) played a large role in promoting grid computing and virtual organizations by developing technology, as well as standards to better facilitate said technology, among diverse groups. The project played a critical part in developing the Globus Toolkit, Open Grid Services Architecture (OGSA), Grid Security Infrastructure (GSI), data management protocols, interoperability standards, and more. ', 
        ],
      },
      {
        heading: 'The True Beginning',
        figures: [
          {
            kind: 'asp-vs-saas',
            afterParagraph: 2,
            title: 'Application Service Provider (ASP) and Software as a Service (SaaS) Comparison - Figure B',
          },
        ],
        paragraphs: [
          'And this history brings us, now, to the beginnings of what is considered to be ‘true’ cloud computing, in so far as all of the aforementioned advancements, while monumental in each of their own rights, were merely leading up to the start of cloud computing, for the purposes of this writing. In other words; time-sharing, packet-switching, networked computing, the ARPANET, distributed computing, grid computing and virtual organizations, and, of course, the rise and further development of the internet, all paved the way for cloud computing as we know it today. From here, I will discuss the formal beginnings of cloud computing between the 1990s to 2000s and its development until today (2024). ',
          'Application Service Providers (ASPs) are considered by some to be the beginning of cloud computing. ASPs, “host and maintain information technology (IT) applications across the Internet [and] offer an alternative to traditional models of IT service for user firms,” (Susarla et al.). Which ASP came first is not obvious. However, one of the earliest and most recognizable ASPs was USinternetworking (USi), founded by Christopher McCleary in 1998. USi hosted popular business software applications like Oracle and PeopleSoft, which were used for accounting, human resources, customer relations, and more. This allowed companies to access the software remotely, for a fee, rather than hosting and installing it themselves. This is very similar to SaaS but there are some key differences, which have been shown in Figure B. Not surprisingly, USi began selling SaaS in 1999. ', 
          'Although ASPs are considered to be the predecessor to SaaS and, therefore, cloud computing in general, to an extent, it may come as a surprise that the term cloud originated a few years prior to 1999.  At first glance, it seems like some of the titans of the cloud industry, Google and AWS, may lay claim to the term’s origin. Indeed, the cloud started to become a widespread term around August 2006, the month in which Eric Schmidt, Chairman and CEO of Google at the time, introduced the term at the Search Engine Strategy Conference in San Jose, California; and the same month in which AWS launched its Elastic Compute Cloud (EC2) service (Barr). ',
          '“But Technology Review tracked the coinage of the term back a decade earlier, to late 1996, and to an office park outside Houston,” (Regalado). A team of technology executives for Compaq Computer had a vision for cloud computing, or cloud computing-enabled applications, as they called it, which dates back to late 1996. ',        
        ],
      },
      {
        heading: 'Cloud Computing Developments by Amazon, Microsoft, and Google',
        figures: [
          {
            kind: 'image',
            afterParagraph: -1,
            title: 'George Favaloro and the 1996 Compaq plan',
            caption:
              'George Favaloro poses with a 1996 Compaq business plan. The document is the earliest known use of the term "cloud computing" in print.',
            imageSrc: '/images/blog/george-favaloro.jpg',
            imageAlt: 'George Favaloro posing with a 1996 Compaq business plan tied to the early use of the term cloud computing.',
          },
          {
            kind: 'major-developments',
            afterParagraph: 7,
            title: 'Major Developments of AWS, Google Cloud, and Microsoft Azure - Figure C',
          },
        ],
        paragraphs: [
          'The top three cloud service vendors are Amazon Web Service (AWS), Microsoft Azure, and Google Cloud (Englander & Wong 442). First to start was AWS who launched their Simple Storage Service (S3) and Elastic Compute Cloud (EC2) in 2006. S3 was a storage as a service (STaaS) and EC2 was an infrastructure as a service (IaaS). Following suit, Microsoft launched Azure Blob Storage in 2008 and Azure Virtual Machines in 2012; and Google launched Google Cloud Storage in 2010 and Google Compute Engine in 2012. Next, AWS launched Elastic Beanstalk, their platform as a service (PaaS), in 2008; Google’s Google App Engine came out in 2011 and Microsoft’s Azure App Service followed in 2015. These big names providing widely available cloud computing services marked the beginning of an explosion of cloud computing, and the new developments did not stop and have not stopped to this day.',
          'The next development was one highly beneficial to users: autoscaling. Autoscaling, in cloud computing, is a feature which automatically adjusts the user’s service based on demand. For example, if a user has an IaaS running and the demand on the machine is low, the service should adjust to a lighter (and less expensive) configuration. Meanwhile, if the demands on the IaaS are high at a given time, the feature should automatically adjust the configuration to be able to handle it, bumping up the expense, but only as needed. Rather than needing to base cloud service purchases based on projected needs, the service could now ‘automatically scale’ to the user’s needs moment-by-moment. This is much more cost-efficient for the buyer, and also allows the service provider to free up their unused machines to offer to other buyers. AWS launched this feature in 2009 and Google and Microsoft followed in 2014. ',
          'Though AWS had been first to launch most major developments at this point, Microsoft actually got the ball rolling on cloud machine learning when they launched Azure Machine Learning in 2014. Google and AWS launched Cloud Machine Learning and SageMaker in 2016 and 2017, respectively, to match. They also took it a step further by launching Vertex AI (Google) in 2021 and SageMaker Studio (Amazon) in 2021 and 2022, respectively. These services made machine learning and AI accessible to virtually everyone, so that users and businesses could leverage their power without necessarily having a field expert working for them. ',
          'While Microsoft was leading the charge in cloud machine learning services with their aforementioned Azure Machine Learning in 2014, AWS wasn’t lagging behind for no reason. They had been working on Lambda, a serverless cloud computing service that launched in 2014. Architectures that were centered around application programming interfaces, or APIs, were increasing leading up to this time. The introduction of widely accessible serverless cloud computing services allowed developers to spend more time writing code and less time managing servers or infrastructure. Of course, Microsoft and Google launched their serverless cloud services, Azure Functions and Google Cloud Functions, in 2016 and 2018, respectively. ',
          'Containerized applications had been on the rise during this period, as well. Unrelated to the big three cloud services, Docker launched in 2013, which allowed applications to be encapsulated in portable containers, and containerized applications became mainstream. Google had also developed a container orchestration platform called Kubernetes due to their large-scale container management experience, and they released it, open-source, in 2015. Cloud services followed, with Google Kubernetes Engine launching in 2014, AWS Elastic Container Service in 2015, and Azure Kubernetes Service in 2017. AWS, actually somewhat late to the game this time, also launched Elastic Kubernetes Service in 2018. ',
          'Unfortunately, not all users and businesses were able to use cloud computing services. Some industries, for example, have regulations that require certain data that may be sensitive to be kept at a certain premises or property. The answer to this issue was hybrid cloud computing: Azure Stack, which launched in 2017, was a set of tools that helped users to utilize cloud servers in their own environments. Azure Arc, their official hybrid cloud platform, rather than just a toolset, was launched in 2019, along with AWS Outposts and Google Cloud Anthos, to the same purpose. These platforms didn’t advance cloud computing ‘forward,’ per se, but did open up accessibility to many who had been limited to local environments rather than true cloud computing. In this way, the width of cloud computing was increased, as opposed to the depth. ',
          'Maybe the most important recent development for cloud computing has been generative AI. “Generative artificial intelligence (AI) opens the door to a novel generation of methods and solutions spaces,” (Chandler & Chalé 52). Microsoft launched Azure OpenAI in 2021, Google launched Gemini in 2023, and AWS launched Bedrock in 2023 as well as Amazon Q in 2024. Notably, Microsoft is a major investor and partner with OpenAI, which, “is an AI research and deployment company [whose] mission is to ensure that artificial general intelligence benefits all of humanity;” (OpenAI). OpenAI is currently famous for creating ChatGPT, perhaps the most standout product in terms of generative AI. This partnership is what allows Azure OpenAI to exist, and solidifies Microsoft’s place as a frontrunner in terms of generative AI. ',
          'While generative AI is substantial in its own right, its connection with cloud computing is still quite meaningful. The most obvious fact is that the best generative AI models require powerful computational resources to run, so the cloud complements this very well by being able to provision scalable infrastructures to support the intense workloads of AI models. Cloud services also provide methods for integrating generative AI into already-existing cloud services like databases, data lakes, and analytics; the generative AI can make these services smarter and more efficient.',
          'Overall, AWS, Google Cloud, and Microsoft Azure each have a lot to offer in terms of cloud computing. But, for the sake of comparison, AWS is a great all-rounder since they have tended to stay on the front-end of new developments. Google, on the other hand, having created kubernetes to begin with, would be a great choice for users or businesses with a focus on containerized applications. Microsoft Azure, though, was very much ahead in terms of machine learning when they released Azure Machine Learning back in 2014, and continue to hold their place as a strong generative AI contender through their partnership with OpenAI and their Azure OpenAI. ',
        ],
      },
      {
        heading: 'Popular Examples of Successful Cloud Computing Implementation',
        paragraphs: [
          'The popular streaming service, Netflix, is a great example of the power of cloud computing. Netflix is responsible for 14.9% of global internet traffic (Armstrong). This requires an excessive amount of computational resourcing to manage. And Netflix uses AWS autoscaling to handle traffic fluctuation, among other things. The idea is that, if there are relatively few people watching Netflix at a given time, the demand for computational resources would also be relatively low. Conversely, if there were many people watching Netflix at once, the computational resource demand would be high. The latter might occur if a new show were recently released. Rather than Netflix guessing or projecting how much computational resourcing would be needed for certain periods and spending money on the amount of cloud resources they thought they would need, AWS is able to provide auto-scaling so that Netflix only spends on what they need at a given time. This not only saves them vast amounts of money directly, but also frees up employee attention so that they can focus on other things rather than traffic projections for the sake of computational resource planning. ',
          'Another great example is Spotify, a popular music streaming platform. Spotify uses Google Cloud’s BigQuery in tandem with Cloud Machine Learning to analyze their data, find trends, and cater to user behavior and preferences. For example, when a user builds a playlist on Spotify, they are able to find ‘suggested’ songs to add to their playlist based on what is already on it. This is, in large part, because Spotify is able to smoothly track a huge amount of user data and analyze it with the help of machine learning to find which songs similar listeners tend to enjoy. This creates a better user experience while also saving Spotify time and money by making it simpler to work with their large amounts of user data. ',
          'Coca-Cola, the famous soft drink company, has leaned into Microsoft Azure heavily. As of April 2024, Coca-Cola has, “migrated all its applications to Microsoft Azure,” (Microsoft). This has helped them in the fields of marketing, manufacturing, managing the supply chain, and more. Coca-Cola even uses Azure OpenAI to help generate personalized marketing content, social media posts, and ad campaigns based on their customers’ preferences. ',        
        ],
      },
      {
        heading: 'Conclusion',
        paragraphs: [
          '	So, cloud computing has its conceptual seeds in time-sharing, Dr. J. C. R. Licklider’s intergalactic computer network, packet-switching, ARPA, the internet, TCP/IP (networked computing), distributed computing, and grid computing and virtual organizations. Its earliest traced use, as a term, is by the business Compaq in 1996. It really came off the ground from the time when ASPs began through when major players began providing cloud computing services, such as when AWS launched in 2006, followed by Microsoft and Google in short order. These major players went on to provide a myriad of various cloud computing services. AWS stands out as an all-around leader in cloud computing, Google has expertise in kubernetes and containerized application orchestration, and Microsoft Azure appears to be leading in machine learning and AI. Cloud computing innovation and new ideas continue to this day, and the world’s leading companies leverage its utility to great benefit. It is unfortunate that Dr. Licklider passed away, not so long ago, in June 1990, because this was so close, relatively, to the emergence and surge of cloud computing. I believe he would be glad to see that his vision for an intergalactic computer network has, for the most part, perhaps achieved and surpassed his dreams via cloud computing. ',        ],
      },
    ],
  },
];
